### ISSUE TITLE
Who made changes to neuronnetwork_netgen?

### ISSUE THREAD

**Issue by Haowii** [gengler1123/PNN#7]
I clicked sync on the desktop github and the code in my compiler is messed up? I dont really get this sync thing, if I commit new u guys can see the changes right? what's the sync for

**Comment by Haowii** [comment]
I think its the GitHub software itself overwrote my code....it copied things like <<<<<new/original into the file. How do I avoid that when i click Sync?

**Comment by Haowii** [comment]
Oh by the way Gary can u see my code? Does the graph look right?

**Comment by Haowii** [comment]
@gengler1123

**Comment by gengler1123** [comment]
sync pulls the code from the repository and puts it on your computer.  So
you get other peoples changes.

GitHub keeps a record of past changes, so you should be able to restore the
previous version of your code.

-Gary

On Thu, Jun 23, 2016 at 2:44 PM, Haowii <notifications@github.com> wrote:

> @gengler1123 <https://github.com/gengler1123>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gengler1123/PNN/issues/7#issuecomment-228146108>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALHKCpDZ78rPbkY_A_cG-pI0Ec4d1LzAks5qOtQggaJpZM4I9DAd>
> .
>



-- 
Gary R. Engler
Ph.D. Candidate
Office: Kidde 105
Office Phone: (201) 216 - 5447
Department of Mathematical Sciences
Stevens Institute of Technology
Hoboken, NJ 07030

**Comment by Haowii** [comment]
I tried to restore but it was unsuccessful, but I fixed it manually.
